common_template_deps = [
    'share/otf2/otf2.types',
    'share/otf2/otf2.enums',
    'share/otf2/otf2.defs',
    'share/otf2/otf2.events',
    'share/otf2/otf2.snaps'
]

templates = [
    [ 'include/otf2/OTF2_GeneralDefinitions.h',
        'OTF2_GeneralDefinitions.tmpl.h',
        'build-config/VERSION' ],
    [ 'include/otf2/OTF2_Definitions.h',
        'OTF2_Definitions.tmpl.h' ],
    [ 'include/otf2/OTF2_Events.h',
        'OTF2_Events.tmpl.h' ],
    [ 'src/otf2_events_int.h',
        'otf2_events_int.tmpl.h' ],
    [ 'include/otf2/OTF2_EvtReaderCallbacks.h',
        'OTF2_EvtReaderCallbacks.tmpl.h' ],
    [ 'src/OTF2_EvtReader_inc.c',
        'OTF2_EvtReader_inc.tmpl.c' ],
    [ 'include/otf2/OTF2_EvtWriter.h',
        'OTF2_EvtWriter.tmpl.h' ],
    [ 'src/OTF2_EvtWriter_inc.c',
        'OTF2_EvtWriter_inc.tmpl.c' ],
    [ 'include/otf2/OTF2_GlobalEvtReaderCallbacks.h',
        'OTF2_GlobalEvtReaderCallbacks.tmpl.h' ],
    [ 'include/otf2/OTF2_GlobalSnapReaderCallbacks.h',
        'OTF2_GlobalSnapReaderCallbacks.tmpl.h' ],
    [ 'src/OTF2_GlobalEvtReader_inc.c',
        'OTF2_GlobalEvtReader_inc.tmpl.c' ],
    [ 'src/OTF2_GlobalSnapReader_inc.c',
        'OTF2_GlobalSnapReader_inc.tmpl.c' ],
    [ 'src/otf2_local_definitions.h',
        'otf2_local_definitions.tmpl.h' ],
    [ 'include/otf2/OTF2_DefReaderCallbacks.h',
        'OTF2_DefReaderCallbacks.tmpl.h' ],
    [ 'src/OTF2_DefReader_inc.c',
        'OTF2_DefReader_inc.tmpl.c' ],
    [ 'include/otf2/OTF2_DefWriter.h',
        'OTF2_DefWriter.tmpl.h' ],
    [ 'src/OTF2_DefWriter_inc.c',
        'OTF2_DefWriter_inc.tmpl.c' ],
    [ 'src/otf2_global_definitions.h',
        'otf2_global_definitions.tmpl.h' ],
    [ 'include/otf2/OTF2_GlobalDefReaderCallbacks.h',
        'OTF2_GlobalDefReaderCallbacks.tmpl.h' ],
    [ 'src/OTF2_GlobalDefReader_inc.c',
        'OTF2_GlobalDefReader_inc.tmpl.c' ],
    [ 'include/otf2/OTF2_GlobalDefWriter.h',
        'OTF2_GlobalDefWriter.tmpl.h' ],
    [ 'src/OTF2_GlobalDefWriter_inc.c',
        'OTF2_GlobalDefWriter_inc.tmpl.c' ],
    [ 'src/otf2_snaps.h',
        'otf2_snaps.tmpl.h' ],
    [ 'include/otf2/OTF2_SnapReaderCallbacks.h',
        'OTF2_SnapReaderCallbacks.tmpl.h' ],
    [ 'src/OTF2_SnapReader_inc.c',
        'OTF2_SnapReader_inc.tmpl.c' ],
    [ 'include/otf2/OTF2_SnapWriter.h',
        'OTF2_SnapWriter.tmpl.h' ],
    [ 'src/OTF2_SnapWriter_inc.c',
        'OTF2_SnapWriter_inc.tmpl.c' ],
    [ 'src/tools/otf2_print/otf2_print_inc.c',
        'otf2_print_inc.tmpl.c' ],
    [ 'src/tools/otf2_print/otf2_print_types.h',
        'otf2_print_types.tmpl.h' ],
    [ 'src/tools/otf2_snapshots/otf2_snapshots_events.hpp',
        'otf2_snapshots_events.tmpl.hpp' ],
    [ 'src/tools/otf2_snapshots/otf2_snapshots_events_inc.cpp',
        'otf2_snapshots_events_inc.tmpl.cpp' ],
    [ 'src/tools/otf2_snapshots/otf2_snapshots_callbacks_inc.cpp',
        'otf2_snapshots_callbacks_inc.tmpl.cpp' ],
    [ 'src/otf2_attribute_list_inc.c',
        'otf2_attribute_list_inc.tmpl.c' ],
    [ 'include/otf2/OTF2_AttributeList.h',
        'OTF2_AttributeList.tmpl.h' ],
    [ 'src/otf2_attic_types.h',
        'otf2_attic_types.tmpl.h' ],
    [ 'doc/doxygen-user/definitions.dox',
        'definitions.tmpl.dox' ],
    [ 'doc/doxygen-user/events.dox',
        'events.tmpl.dox' ],
    [ 'doc/doxygen-user/snaps.dox',
        'snaps.tmpl.dox' ],
    [ 'templates/example.cc',
        'example.tmpl.cc' ],
]
